version: '3.8'

services:

 db:
  image: mysql:8
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: db_pass123
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wpuser
    MYSQL_PASSWORD: wppassword
  volumes:
    - db_data:/var/lib/mysql
  networks:
    - back-tier

 wordpress:
  image: wordpress:latest
  restart: always
  ports:
    - "8080:80"
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: wpuser
    WORDPRESS_DB_PASSWORD: wppassword
    WORDPRESS_DB_NAME: wordpress

  depends_on:
    - db
  networks:
    - front-tier
    - back-tier
      
volumes:
   db_data:
  
networks:
   front-tier:
   back-tier: